### ISSUE TITLE
Erweiterungen und Änderungen

### ISSUE THREAD

**Issue by Zatraka** [theSaschaM/BSFI22D_Primus#4]
# kleine Erweiterungen:
-  Option zwischen Darkmode und Lightmod hin und her zu switchen.
-  Modale-Dialog-Fenster bei drüber gehen von bestimmten Bereichen einführen.
- Ausdruck-Funktion für bestimmte Dokumente so das man dem User bestimmte Infomationen zukommen lassen kann.

# mittlere Erweiterungen:
- Grafische Analysen der User auf einer oder mehren eigenen Seite.
    - grafische Darstellung der Einnahmen und Kosten des Vereins.
    - grafische Darstellung der  Mitglieder die austreten oder dazu kommen.
    - grafische Darstellung wie viele Mitgleider anwesen wären. Soll nicht nur Monatlich angezeigt werden können sondern soll auch 
       jährlich oder auch wöchentlich angezeigt werden.

# große Erweiterungen :
- Einheitliches Design
    - keine inline <styles> in der Html Datei. Soll alles in eigenen CSS-Dateien ausgelagert werden.
    - Inhalte wie z.B. Sidebars auch auslagern und so verwenden das jede Seite die eine Sidebar benutzt die gleiche benutzt.
- User Anmeldungsverfahren.
    - Umgestaltung hinzufügen von weiteren Websiten und Änderungen am Datenbankenmodell
        - User legt sein eigenes Profil an.
        - Der User wählt das Angebot selber aus.
        - Der User benutzt den Check in selber.
        - Der User ist selber in der Lage Waffen über seinem Account zu kaufen.(Wenn er die Berechtigung besitzt)
-

**Comment by theSaschaM** [comment]
Ich werde im Folgenden einfach mal schriftlich Stellung zu deinem Ticket beziehen und hierfür auch deine Überschriften nutzen:

# Kleine Erweiterungen:
Light und Darkmode klingen zwar schön, sind jedoch nicht unbedingt eine kleine Erweiterung. Du musst nämlich an einem Ort zentral die Farben verwalten und diese überall auf sämtlichen Seiten nutzen. Das muss in unserem MVC-Konzept beachtet werden. Ich werde es berücksichtigen, jedoch keinerlei große Priorität stellen.

Modale-Dialogfelder sind eigenständige Fenster, welche dem Nutzer eine Info anzeigen. Zum Beispiel "Es ist ein Fehler aufgetreten" und dazu ein Button "OK". Was du meinst sind Tooltips. Modal-Dialogfenster sind innerhalb der Webentwicklung nämlich keinesfalls gängig und würde ich von Grund auf auch weglassen wollen, da es hier zu keinem solchen Fall kommen sollte, wo dies notwendig wird. Bezüglich der Tooltips habe ich dir aber auch bereits ein CSS-Framework gezeigt, falls du dich erinnerst. Entsprechend hat dies auch keine große Priorität.

"Ausdruck"-Funktionen benötigen wir nicht. Dies hat damit zu tun, dass wir unsere Benutzeroberfläche ohnehin Webbasiert aufbauen. Entsprechend können wir diese Funktionalität leicht anbieten, ohne selbst diese Funktionalität groß einbauen zu müssen.

# Mittlere Erweiterungen:
Ggf. too much. Wir sollen hauptsächlich Nutzer verwalten und kein Analyse-Tool schreiben. EIne einfache Abfrage, vielleicht noch einen Graph bezüglich der Einnahmen ist angemessen und auch realistisch, mehr jedoch nicht.

# Große Erweiterungen:
Die Auslagerung unseres CSS-Styles ist keine Erweiterung sondern ein Grundprinzip, welches ich erwarte für unser Projekt. Ich möchte nicht, wenn ich das Design einer Web-Platform abändern will dies manuell über mehrere Dateien regeln. Entsprechend auch Singular (Datei) und nicht Plural (Dateien).

Außerdem braucht der Nutzer kein eigenes Profil an zu legen. Es geht darum, dass der Besitzer des Schießvereins seine Mitglieder verwalten können soll. Dies ist unser Auftrag und daran werden wir uns auch hauptsächlich orientieren. Eine externe Nutzer-Anmeldung ist da schon ein komplettes weiteres System und schießt (wortwitz mit Schießverein intended^^) übers Ziel hinaus. Der fiktive Besitzer des Schießvereins wollte kein All-Around-Setup mit Website, SEO-Lösung, Vorabanmeldung, etc., sondern einfach nur nicht mehr mit einer Excel Datei seine Aufgaben Lösen

**Comment by theSaschaM** [comment]
Um Ansonsten allerdings meine eigenen Ansätze hinzuzusetzen und nicht nur andere kleinere Erweiterungen zu kritisieren, hier auch noch meine kleinen Vorschläge zur einfachen Verbesserung von dem:

# Backup-System
Wir könnten ein einfaches Backup-System einführen, welches ein kurzes Popup bereitstellt in Richtung "Jo, hast schon seit ein paar Tagen kein Backup mehr gemacht. Klick hier um eines durch zu führen" und dann wird dies auf ein zweites seperates (z.B. in einer ini-Datei konfiguriertes) Laufwerk abgespeichert. Dies ist eine einfache Änderung, da wir die Datenbank mit SQLite machen und dies letztlich auch nur eine Art Datei ist.

# API
Wir könnten für die anderen Nutzeranmeldungen eine offene API bereitstellen, mit welcher sich unser System mit einem späteren anderen System (ggf. bei einer Website mit Nutzeranmeldung) integrieren lässt.

# Video als Nutzeranleitung
Eine Bildschirmaufnahme von einem Sachverhalt zu machen und dies kurz zu erklären währenddessen ist kein großer Aufwand, lässt sich einfach in eine Website integrieren und erhöht wesentlich die Usability der Software. Weil sind wir mal ehrlich: Wer (außer Entwickler) liest sich schon Benutzeranleitungen durch?

# Multiplatform - Windows und Linux
Das Backend wird höchstwahrscheinlich in C++ geschrieben. Die meisten Webframeworks sind jedoch platformunabhängig, was bedeutet, dass diese lediglich für die jeweilige Platform neu kompiliert werden müssen um dorthin exporiert werden zu können. Windows und Linux sollte hierbei also ein einfaches Ziel sein, welches sich leicht umsetzen lässt. Gleichzeitig wäre dann ein kleines System, wie z.B. ein Raspberry Pi, als Server möglich.
Und unser Front-End ist ohnehin Webbasiert, weshalb das auch dort keinesfalls ein Problem sein dürfte.
